### ISSUE TITLE
MutatingWebhookConfiguration spec is invalid

### ISSUE THREAD

**Issue by marcus-sa** [spotinst/ocean-right-sizing-mutator#2]
**What happened**:
Following the installation instructions, the apply will fail because the `MutatingWebhookConfiguration` spec is invalid/outdated
```
secret/ocean-rs-mutator-secret created
error: error validating "deployment/mutatingwebhook-cabundle.yaml": error validating data: [ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "sideEffects" in io.k8s.api.admissionregistration.v1.MutatingWebhook, ValidationError(MutatingWebhookConfiguration.webhooks[0]): missing required field "admissionReviewVersions" in io.k8s.api.admissionregistration.v1.MutatingWebhook]; if you choose to ignore these errors, turn validation off with --validate=false
make: *** [Makefile:20: gencerts-deploy] Error 1
```

**What you expected to happen**:
For the `MutatingWebhookConfiguration` to be applied

**How to reproduce it (as minimally and precisely as possible):**
Try to install.

**Environment:**

- Operator version: master
- Cluster version: `version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by caiofralmeida** [comment]
@marcus-sa I think you should change the `MutatingWebhookConfiguration` api version to `admissionregistration.k8s.io/v1beta1`, probably because of the Kubernetes version compability.

Change the template file in `deployment/mutatingwebhook-template.tmpl`

e.g:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: ocean-rs-mutator-webhook-cfg
  labels:
    app: ocean-rs-mutator
webhooks:
  - name: ocean-rs-mutator.cluster.local
    clientConfig:
      service:
        name: ocean-rs-mutator-svc
        namespace: kube-system
        path: "/ocean-rs-mutator"
      caBundle: %CA_BUNDLE%
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    objectSelector:
      matchLabels:
        spot.io/mutate-resource: enabled
    namespaceSelector:
      matchLabels:
        spot.io/mutate-resource: enabled
```
